### ISSUE TITLE
String与&str概念解析的链接失效

### ISSUE THREAD

**Issue by AsakusaRinne** [sunface/rust-course#1038]
[这个文档](https://zh.practice.rs/collections/String.html)里的链接“易混淆概念解析 - &str 和 String (https://course.rs/confonding/string.html)” 失效了

**Comment by sunface** [comment]
现在改成 `https://course.rs/difficulties/string.html` 了，可以提一个 PR :)

**Comment by AsakusaRinne** [comment]
好的，PR已经提在了**rust-by-practice**这个项目里。:)

**Comment by sunface** [comment]
谢谢～～😆
