### ISSUE TITLE
中文 -> 英文翻译

### ISSUE THREAD

**Issue by sunface** [sunface/rust-course#105]
本书的内容渐渐丰满起来，可以开始翻译成英文版了。

但是由于我这边所有时间需要投入到中文内容上，因此需要1-2个核心协作者，咱一起做这件事。

**Comment by ZvanYang** [comment]
我没有rust经验，但是希望参加

我主要使用语言是PHP和go，以后还是想学习一下rust

**Comment by sunface** [comment]
可以的。。非常欢迎，你可以先通过这本书深入学习下Rust，后面准备好了，联系我：）

**Comment by Jun10ng** [comment]
我也希望参加，目前主要语言是go，也是抱着学习rust的心态来的。

**Comment by sunface** [comment]
> 我也希望参加，目前主要语言是go，也是抱着学习rust的心态来的。
> 此外，提个意见：在阅读在中文版本过程中，会看到一些两性笑话的比喻，在翻译的过程中最好删除掉。我个人意见是中文版也删掉。你觉得呢？ @sunface

非常有道理。。其实我也想删掉的，哈哈

**Comment by sunface** [comment]
教程还是专心在中文上，暂不考虑英文翻译。
