### ISSUE TITLE
文档中的内容应当保持文明和谐

### ISSUE THREAD

**Issue by ShuiHuo** [sunface/rust-course#1085]
文档不要插入脏话等让人反感的内容。
反面例子：
![[块注释](https://course.rs/basic/comment.html#%E5%9D%97%E6%B3%A8%E9%87%8A--)](https://user-images.githubusercontent.com/7471938/201308230-fd867bba-a2cc-4bb8-9cc5-39d1d82ea232.jpg)

**Comment by sunface** [comment]
好的，谢谢建议！
