### ISSUE TITLE
应当注意细节考证上存在的问题

### ISSUE THREAD

**Issue by longguzzz** [sunface/rust-course#1088]
最近开始学Rust，看了《Rust语言圣经》的一些内容，发现有部分表述存在逻辑矛盾，另外有一些内容细节似乎和其他文本材料如《The Rust Reference》、《The Rust Programming Language》冲突，故开此issue做考究文，希望为Rust社区做一点贡献。

首先应该说的是，本书在“常量”、“不可变变量”等细节上非常考究，这是非常棒的一点！👍尤其是编译器软件视角、硬件机器视角上的解读，对于区分这两个概念是很有帮助的。同时，这也会传递出一种信息：作者们对于细节非常考究。但这也是一把双刃剑：读者认为非常文中内容考究的认知会放大那些未经考究的错误的影响。

所以，希望诸位作者能尽量考证其中的内容，谨慎行文。既然有意将此开源书做成“圣”级别的材料，并且读者亦可能如此认为，那么应该尤其注重内容取材以及加工过程。因为内容错误的内容不是在此处一时错，错误的内容会经由读者广泛传播。读者越多、Starred越多、越是称“圣”之名，则越是应该细查。

## 例1，[基本类型](https://course.rs/basic/base-type/index.html#%E5%9F%BA%E6%9C%AC%E7%B1%BB%E5%9E%8B)介绍中的错误

> 数值类型: 有符号整数 (i8, i16, i32, i64, isize)、 无符号整数 (u8, u16, u32, u64, usize) 、浮点数 (f32, f64)、以及有理数、复数
> 字符串：字符串字面量和字符串切片 &str

《Rust语言圣经》的[有理数和复数](https://course.rs/basic/base-type/numbers.html#%E6%9C%89%E7%90%86%E6%95%B0%E5%92%8C%E5%A4%8D%E6%95%B0)的部分有提及，有理数、复数不是标准库中的类型，也不是内置类型，是数值库：[num](https://crates.io/crates/num)中的类型，自然也就不是基本类型，那么也就与[基本类型](https://course.rs/basic/base-type/index.html#%E5%9F%BA%E6%9C%AC%E7%B1%BB%E5%9E%8B)所言在逻辑上不一致。

那么根据readme文件，文中这部分是引用自Rust语言实战？也就是《Rust in Action》吗？

但是经过翻阅《Rust实战》第2章 Rust语言基础 的 2.3 数字类型这部分，实际上里面并没有这样的介绍。里面的目录结构是

> 2.3 数字类型这部分
2.3.1 整数和浮点数
2.3.2 整数的二进制、八进制及十六进制表示法
2.3.3 数字的比较运算
2.3.4 有理数、复数和其他数字类型

其中有理数、复数是分开介绍，并未将其当作基本类型。文中亦未见类似内容。

查阅《Rust in Action》的 2.3 Numbers 部分

> Integers and decimal (floating-point) numbers 
Integers with base 2, base 8, and base 16 notation 
Comparing numbers 
Rational, complex numbers, and other numeric types

在结构上也是相似的，但文中亦未出现类似内容。

如果在google上查，最早在2022年3月14日有一篇[【Fitz】Rust 基本类型](https://www.cnblogs.com/fitznotes/articles/16005706.html)出现相同内容。但经过git查看2022年2月的《Rust语言圣经》版本，《Rust语言圣经》已有该部分内容。所以应该是该博客引用《Rust语言圣经》中的内容。截至目前网络上大约只有50份笔记受此影响：

> ![image](https://user-images.githubusercontent.com/96779663/201520599-0eb25224-9795-4c90-991a-37395269d45b.png)

这便是内容不细究会造成的危害——**在所有复制引用的地方会传播同样的错误**。依以上分析，《Rust in Action》中本无该错误，该错误是在写书过程中产生的。并在第二级材料“阅读笔记”上进行了小范围传播。**所以，此类问题实在不可不察也。**

未来《Rust语言圣经》的影响力会越来越大，因而，希望能够尽量阻断此类的错误：最好不是在读者考究细节感觉疑惑时来发现，而是在作书过程中就尽量预防。

## 例2，[2.2.3. 语句与表达式](https://course.rs/basic/base-type/statement-expression.html)中的逻辑矛盾

或许例1不是什么问题，因为不大会影响到实际编程。但是这里的问题会影响对Rust的理解。而Rust偏偏需要理解对了才能写对，所以此类错误应当特别重视。

1. > Rust 的函数体是由一系列语句组成，最后由一个表达式来返回值
2. > 语句会执行一些操作但是不会返回一个值，而表达式会在求值后返回一个值
4. > 一旦你在表达式后加上分号，它就会变成一条语句，再也不会返回一个值，请牢记！
5. > 最后，表达式如果不返回任何值，会隐式地返回一个 ()

“字符串字面量”也不应当视作一种类型。字面量[Literal (computer programming) - Wikipedia](https://en.wikipedia.org/wiki/Literal_(computer_programming))是一种数据表示的记法，就像i32的字面量可以是0x2也可以是2，还可以是0o2，这种记法和类型系统并非一回事。

另外，字符串切片也不是基本类型……Rust has only one string type in the core language, which is the string slice str that is usually seen in its borrowed form &str，见《The Rust Programming Language》的 8.2. Storing UTF-8 Encoded Text with Strings，slice是[T]，但由于基本用的是shared slice，也就是&[T]，所以一般也把&[T]叫slice。因而这段话里的the string slice str实际上不是the shared string slice &str。只有str才是基本类型，&str并不是基本类型。
https://doc.rust-lang.org/reference/types/textual.html
https://doc.rust-lang.org/reference/types/slice.html

详细讨论如图：
> ![image](https://user-images.githubusercontent.com/96779663/201519012-40ebedba-b6fa-46b9-a29a-cc0fec2b52c9.png)

由此，第二个危害在于，**后面所有强依赖于此内容的内容，在理解逻辑上都会潜藏隐患**。尤其是表达式、语句这样的概念，后面应该有大量的内容建立在此之上。**所以，此类问题实在不可不察也。**

细节不考究的第三个危害便是，**可能让读者心生怀疑：如果这么重要，并且**看上去已然非常考究的概念**，却存在逻辑表述上的混乱，并且其他小细节上似乎也高频地出现差错，那么其他内容的精准度是不是要打一个问号呢？**产生了此类疑问的读者只能去各处对照不同的说法。（虽然，学各种语言其实最后也都免不了对照各家材料，甚至找AST、编译器什么的……但难免会期望能一开始就从领域内的“圣”书中建立一个基本正确的认知框架……最让人可能panic的情景是，内容错误导致理解错误，由此埋下了看着正确实际错误的bug）**所以，此类问题实在不可不察也。**

## 期望

如果要修复此类问题，可能是个系统工程，或许要比较久的时间。但是，

> 截至目前，Rust语言圣经已写了170余章，110余万字，历经800多个小时，每一个章节都是手动写就，没有任何机翻和质量上的妥协（相信深入阅读过的读者都能体会到这一点）。

所以我相信，在此三类问题上也必然不会妥协。而且，也相信借助开源社区的力量，或许用几个月或者用一两年可以逐步解决。

总而言之，就目前来看，《Rust语言圣经》结合数据在硬件中的表示方式进行概念解释、结合练习来讲解、语言轻松愉快……**即使有错误的地方，通过练习也能大体解决。总体上瑕不掩瑜，希望未来越来越好。**

如果此后发现其他细节上的问题，会在本issue中更新。

**Comment by longguzzz** [comment]
[2.3.1. 所有权](https://course.rs/basic/ownership/ownership.html)

《The Rust Programming Language》的[What is Ownership? - The Rust Programming Language](https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html)里面是`Stack-Only Data: Copy`，对于只存在于栈上（而不存在于堆上）的数据会Copy

《Rust语言圣经》[2d17b02](https://github.com/sunface/rust-course/commit/2d17b02d5a7dca36ef097f03f0f8f10e83a8c9a1)翻译成`浅拷贝只发生在栈上`不合适吧？也就是说，在堆上不会发生浅拷贝？

这两个意思完全不一样啊……

**Comment by sunface** [comment]
有理有据，感谢你的建议~~回复有些晚了，抱歉哈~~
