### ISSUE TITLE
fix: 修正「数值类型」总结内容

### ISSUE THREAD

**Issue by l1ch40** [sunface/rust-course#112]
> Rust的数值上可以使用方法. 例如你可以用以下方法来**将24.5取整: 13.14**_f32.round(), 在这里我们使用了类型后缀，因为编译器需要知道13.14的具体类型

不是将 24.5 取整，应是将 13.14 取整。

PR: https://github.com/sunface/rust-course/pull/111

**Comment by sunface** [comment]
非常感谢，已合并
