### ISSUE TITLE
关于所有权一节中"不可变引用 &T ，例如转移所有权中的最后一个例子，但是注意: 可变引用 &mut T 是不可以 Copy的"疑问？

### ISSUE THREAD

**Issue by yao1019** [sunface/rust-course#1121]
我的理解是可变引用如果不是copy是不是意味着转移了所有权，那么假设有let s1=&mut str;当把s1传递给一个函数时，是否所有权转移到该函数，那么s1将不再有效，实际测试时函数返回后依旧可以使用s1,似乎又表明可变引用是copy的？求解答。

**Comment by 1654364091** [comment]
请问有结论了吗？我也遇到了这个疑惑
