### ISSUE TITLE
[FAQ] 关于泛型一章的引导语讨论

### ISSUE THREAD

**Issue by niconical** [sunface/rust-course#1231]
目前的[泛型一章](https://course.rs/basic/trait/generic.html#%E6%B3%9B%E5%9E%8B-generics)的引导语是：

"Go 语言在 2022 年，就要正式引入泛型，被视为在 1.0 版本后，语言特性发展迈出的一大步，为什么泛型这么重要？到底什么是泛型？Rust 的泛型有几种？ 本章将一一为你讲解。"

这里用了 Go 引入泛型对 Go 造成的巨大影响来吸引读者，但是 Go 泛型和 Rust 泛型相差甚远（我个人也很讨厌 Go 泛型）。似乎这里文案可以提及泛型本身的有趣之处来吸引读者，而且读者可能不一定了解 Go 以及 Go 泛型对 Go 的影响。

以下是一些替代文案，由 GPT3.5 生成，作为参考：

- “Rust 的一个强大的特性是它提供了一套强大且灵活的泛型系统。与 C++泛型代码的模板元编程相比，Rust 允许程序员编写易于阅读、正确性检查良好的泛型代码。 此外，泛型代码还能够提高程序的可重用性和性能。在这本章，我们将探讨 Rust 语言的泛型系统。我们会从泛型的原理和使用场景等基础知识开始，逐步深入到泛型约束和 trait 等高级特性，以帮助您写出更加通用和可靠的 Rust 代码。让我们开始吧！”

- “泛型可以让您编写可以在不同类型上工作的代码，而无需在每种情况下单独实现相同的功能。这是提高程序性能和可重用性的一种强大方式。在使用泛型时，Rust 还将确保代码的类型安全，从而避免由于类型错误引起的运行时错误。因此，在使用 Rust 进行系统级编程和构建高性能应用程序时，掌握泛型编程技巧是至关重要的。在这本电子书中，我们将解释 Rust 泛型的基本原理和使用场景，以及更具体和高级的语言功能，如泛型约束和 trait。接下来，一起探索 Rust 泛型编程的奇妙世界”

**Comment by sunface** [comment]
谢谢建议，不过还是保留以前的吧，GPT给出的太书面了，引导语，我希望放一些不那么书面的东东 :P
