### ISSUE TITLE
左右翻页键在最下面，需要翻完所有评论，有点麻烦

### ISSUE THREAD

**Issue by heygsc** [sunface/rust-course#1266]
左右翻页键在最下面，有的评论有点多，需要往下翻。
或者点击左侧目录栏，才能切换下一页。

如果把翻页键直接固定定位，或者放在文章末尾-评论区前面，是不是好一点

**Comment by sunface** [comment]
好的。。。谢谢建议

**Comment by heygsc** [comment]
这是用的mdbook的话，不知道好不好改，或许需要额外做吧
