### ISSUE TITLE
这个mdbook项目是如何实现page-content的？

### ISSUE THREAD

**Issue by codecoron** [sunface/rust-course#1273]
1. 手动试了一下mdbook项目，但是发现默认没有像作者一样的大纲导航。
2. 手动clone了作者这个项目，发现关键是一个自定义了`custom.js` 和 `theme/index.hbs` `theme/style.css`，`custom.js`中会从`Array`中获取每个md文件的标题，然后处理数据，最后送到`index.hbs`渲染出来
3. 请问，`custom.js`中的数据是怎么获取的？

**Comment by codecoron** [comment]
是不清楚`custom.js`中`Array`的数据是怎么获取的。比如`Array`是如何拿到每个md文档的标题

**Comment by codecoron** [comment]
另外想问下，你这个项目不支持中文搜索，我记得原生mdbook项目是支持中文搜索的

**Comment by Yunkou** [comment]
核心代码在这：
https://github.com/sunface/rust-course/blob/7e45cdea50de6ae17d1a2acd33aea3c6afcf0711/assets/custom.js#L49-L73

- 通过 class 为 header 的拿到目录 （每个标题都有个 class为 header 的 a 标签）
- 遍历 elements  将大纲添加到 pagetoc
-  通过 a 的父标签判断登记，增加缩进

**Comment by Yunkou** [comment]
@sunface  这个 Issues 可以关闭了

**Comment by sunface** [comment]
好的
