### ISSUE TITLE
13章 手把手带你实现链表，除章节首页，其他页面都404文件找不到

### ISSUE THREAD

**Issue by asuper0** [sunface/rust-course#1276]
阅读页面出问题404，但是看了下src文件夹下是有内容的

**Comment by rushChen131** [comment]
link  出现问题了吧

**Comment by Runtus** [comment]
<img width="663" alt="image" src="https://github.com/sunface/rust-course/assets/48038769/9b3a41e5-2bcf-43f0-b437-47551c1f336f">
现在部署在github-page上的网页直接缺了一些文件，感觉是刚才更新github-page时出现的问题

**Comment by sunface** [comment]
问题已解决。。。非常感谢
