### ISSUE TITLE
打开阅读不了，很多都404和加载样式也不对

### ISSUE THREAD

**Issue by KingPuiWong** [sunface/rust-course#1278]

**Comment by KingPuiWong** [comment]
有人能联系一下作者吗？大概率是2小时前的部署导致的，本来看得好好的

**Comment by sunface** [comment]
好的，谢谢。。。没改什么啊 = ， =

**Comment by sillykelvin** [comment]
一样的问题，有很多资源404了，以这个css为例：https://course.rs/css/variables.css

**Comment by sunface** [comment]
问题已解决。。。非常感谢

**Comment by sillykelvin** [comment]
@sunface 辛苦了，不过...好像我这边还是没恢复，还是404

**Comment by sunface** [comment]
> @sunface 辛苦了，不过...好像我这边还是没恢复，还是404

清一下缓存试试 :)
