### ISSUE TITLE
【关于版权】是否可以摘要该教程+少数个人理解作为笔记发布于个人网站

### ISSUE THREAD

**Issue by Justin3go** [sunface/rust-course#1314]
你好，首先该教程我学到很多东西，这里表示感谢。

我看到readme中写着：

> 在开源版权上，我们选择了 [No License](https://www.google.com.hk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwigkv-KtMT0AhXFdXAKHdI4BCcQFnoECAQQAw&url=https%3A%2F%2Fchoosealicense.com%2Fno-permission%2F&usg=AOvVaw3M2Q4IbdhnpJ2K71TF7SPB)，这意味着读者可以随意的 fork 和阅读，但是不能私下修改后再包装分发，如果有这方面的需求，请联系我们，望理解。

我在学习过程中的根据平常习惯做了一些笔记，方便自己索引记忆，基本上对于其他人是不利于阅读的。不知道是否可以发布在个人博客上，像这样:[justin3go.com/s?u=1321d80dbfe](https://justin3go.com/s?u=1321d80dbfe)

目前已经发布方便演示，如果不行的话将立即下架

**Comment by sunface** [comment]
你好，没问题哈

**Comment by yuhao00** [comment]
你小子是来给blog打广告的吧(doge

**Comment by Justin3go** [comment]
算是有20%的这个原因🤣，但主要还是担心no license
