### ISSUE TITLE
网站样式有问题，导航栏收不起来

### ISSUE THREAD

**Issue by theajack** [sunface/rust-course#1330]
网站样式有问题，导航栏收不起来了，手机上没法看了 
![image](https://github.com/sunface/rust-course/assets/23377279/5fb8bfc6-9232-4276-9731-a15817764f0e)

**Comment by sunface** [comment]
我看看。。

**Comment by sunface** [comment]
已解决  https://github.com/sunface/rust-course/commit/d3ecbc208896d67c694568e3257bed896f066e55
