### ISSUE TITLE
【2.4.1. 字符串与切片】的【课后练习】的【String】的网页404了

### ISSUE THREAD

**Issue by devyishan** [sunface/rust-course#1359]
https://zh.practice.rs/collections/String.html

![image](https://github.com/sunface/rust-course/assets/156085664/2c846e10-b95f-4831-86da-9e766727424c)

![image](https://github.com/sunface/rust-course/assets/156085664/6ed648b0-606d-4fe9-8297-c097803c1915)

**Comment by sunface** [comment]
感谢反馈，已解决
