### ISSUE TITLE
入口链接 404

### ISSUE THREAD

**Issue by wfk007** [sunface/rust-course#1364]
访问 https://course.rs 301 到 https://course.rs/about-book.html 然后 404

**Comment by Pilchards** [comment]
午饭回来，正准备潜心学习一下，然后突如其来的404打断了学习的热情

**Comment by atomMacros** [comment]
确实是404了

**Comment by PCKxin** [comment]
怎么突然没了

**Comment by shaoguoji** [comment]
Jekyll 页面构建失败了，看上去像某个 MD 语法有误？ https://github.com/sunface/rust-course/actions/runs/7636240657/job/20802975144

**Comment by programmer-sugar9527** [comment]
编译失败了？

**Comment by bing1zhi2** [comment]
猛地以为作者删除了

**Comment by TomContral** [comment]
好多人啊 😢 我还以为是我自己的问题

**Comment by buibuiKun** [comment]
还以为网络问题

**Comment by sunface** [comment]
我看一下。。

**Comment by sunface** [comment]
已恢复，感谢大家的反馈

**Comment by PCKxin** [comment]
没有样式啊哥

**Comment by Monkey-Z** [comment]
太好了，可以继续愉快的学习啦。刚才不能访问，一时间竟不知道该干点啥 😂
