### ISSUE TITLE
为什么这个教程这么复杂

### ISSUE THREAD

**Issue by bird00101011** [sunface/rust-course#1439]
吗的，为个语法问题，能搞要一天，程序都无法运行起来，各种报错，呵呵

**Comment by rtpacks** [comment]
又没逼着你看，搞笑呢这是，人品不高智商低，有事只会瞎胡诌。

**Comment by bird00101011** [comment]
哦？那你能让rust程序跑起来吗？你会代码？

**Comment by xiao-k233** [comment]
又没逼着你看，搞笑呢这是，对教程的恶意这么大。

**Comment by 17998384** [comment]
你就你妈的一个小丑，自己傻逼呵呵的学不会狗叫什么？

**Comment by 291230769** [comment]
写的很好了，我是受益匪浅

**Comment by bird00101011** [comment]
这门语言我从2015年开始关注，至今不知道是做什么的。本人精通c，php，python，pascal，java,可以这么说，在快速解决问题方面，很容易用这5门编程语言完成。相反，rust可以说对我来说毫无用处，在遇到问题的时候，压根就不会轮到rust上场的机会。

如果说学rust是为了修仙，我看不如去玩scala，反正又不靠这个吃饭。

至于什么整了一天程序员没跑起来，可能吗？智商呢？这么单纯？

我认为，rust至少要拿出点应用领域侧重点并且这个领域是现实中确实符合时代的，否则，只能说是个多余的，或许存在就不应该。

我只是提醒小白，不要想抄近路，什么靠学一门编程语言，rust，就能少走弯路，这是不可能的。不走弯路，等于无知，无知等于技术差，具体更多的内幕，我就不多说了，培训机构又开始蠢蠢欲动了吧，我看您们炒冷饭能卖到何时。

如果说你觉得我说的是错的，ok，那最好证明你是对的，这过分吗？我估计给您的挖个坑，python最牛逼的库，很多人都会爬不出来吧，哈哈哈，这才是真的蠢
________________________________
发件人: Kinono ***@***.***>
发送时间: 2024年7月23日 15:31
收件人: sunface/rust-course ***@***.***>
抄送: bird00101011 ***@***.***>; Author ***@***.***>
主题: Re: [sunface/rust-course] 为什么这个教程这么复杂 (Issue #1439)


写的很好了，我是受益匪浅

―

**Comment by Y-ZD-heheka** [comment]
你的发言是如此目中无人，看你的仓库又啥都没有，语言只是表达思想的工具，你却以会多种语言为傲，请问您2015年是几年级？

**Comment by MochiXu** [comment]
> 你的发言是如此目中无人，看你的仓库又啥都没有，语言只是表达思想的工具，你却以会多种语言为傲，请问您2015年是几年级？

不用跟他计较😂，他的仓库里面很干净，也没有参与任何开源项目，感觉能说出这话的人绝对水平一般（很 low）。
现在很多新兴的数据库，都在用 Rust 构建，Rust 的安全性是 C++ 无法比拟的。

**Comment by sunface** [comment]
偏见与傲慢

**Comment by ifdelete** [comment]
既然能做到精通这么多语言，那么英文文档应该能看懂的,给你指个路
> https://www.rust-lang.org/

**Comment by 17998384** [comment]
你她妈就是个傻逼
