### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by wjw99830** [sunface/rust-course#151]
![image](https://user-images.githubusercontent.com/30546882/148725579-deb587e5-5bd5-47d2-af69-9d21c328bd2b.png)
是零开销抽象吗？

**Comment by sunface** [comment]
你说的对。。。可以帮忙提一个PR:)

**Comment by wjw99830** [comment]
如果下班早的话，可以试试（doge

**Comment by sunface** [comment]
fixed。。
