### ISSUE TITLE
借鉴的内容若无相关协议授权应该标明来源

### ISSUE THREAD

**Issue by zjp-CN** [sunface/rust-course#153]
首先感谢所有编写者的努力，做开源书籍非常不容易。因为我也是 Rust 开源书籍的翻译爱好者。

但是这个项目让我觉得不太舒服。比如 REAME 中这样的内容：

> 本书在内容上部分借鉴了以下书籍，特此感谢：
> - Rust Book
> - ...

原 Rust 官方项目书籍，它们自身带有 MIT 或 APACHE 许可，你们的书中，每处内容，但凡参考（或者翻译）了 Rust 官方项目书籍（以及任何其他有明确版权的资料），最好以链接形式放到每章的末尾。

这个工作并不难：
- 组织各种资料的作者肯定清楚这些资料从何而来，所以每次把资料来源放到末尾就好了。
- 而且现有的很多 TODO 章节都有链接，比如[这样](https://course.rs/memory/layout.html)，所以当它们被完善的时候不要移除掉链接，放到末尾。

虽然 rust-course 是 No License 的，但**参考别的有版权的内容时，不应不带任何声明地使用**。

一个好的例子是张汉东老师的公众号【觉学社】，他的文章虽然不是全部原创，但和你们一样做着翻译和组织资料的事情，而他就罗列了所有参考资料的链接。[例子](https://mp.weixin.qq.com/s/OdcLb5U8QCeYH08feThN7w)。

当你们的书籍变成这样时：

> 本书在内容上部分借鉴了以下书籍：
> - Rust Book
> - ...
>
> **所有的参考内容：均以链接形式标明来源，并且版权遵照原文。**

而不是空洞地说“借鉴”（避免混淆版权界限[招致麻烦](https://github.com/sunface/rust-course/issues/91)），

那么就很完美啦。

**Comment by sunface** [comment]
感谢提醒，但是我觉得有几点还是要声明下：
1. 任何资料的写成都或多或少借鉴了其它资料
2. 本书并不是简单的翻译，如果你认真读的话，所有的内容都是经过精心设计和精密组织的
3. 如果每一章都这样写，那会有大量的参考链接，会非常影响体验，所以我统一放在readme的很显眼的地方进行了标明

最后，还是请认真读完书，若你觉得我还是抄袭了，再来说好吗？

**Comment by sunface** [comment]
感谢提醒，但是我觉得有几点还是要声明下：

1. 任何资料的写成都或多或少借鉴了其它资料
2. 本书并不是简单的翻译，如果你认真读的话，所有的内容都是经过精心设计和精密组织的
3. 如果每一章都这样写，那会有大量的参考链接， 会非常影响体验（因为几乎所有文章都参考了大量的资料，然后通过自己的语言组织和描述出来)，所以我统一放在readme的很显眼的地方进行了标明

当然，你提的建议和意见我这边会看看怎么更好的采纳，谢谢了

**Comment by sunface** [comment]
还有，以rust book为例，这本书是MIT + Apache协议，实际上若没有特殊说明，我是可以选择[任意一个协议遵守的](https://www.quora.com/If-I-modify-code-that-is-dual-licensed-under-the-GPL-and-an-MIT-license-are-there-are-any-issues-releasing-my-modified-code-under-an-Apache-2.0-license).

当然，若我理解有误，欢迎指出。

**Comment by sunface** [comment]
还有，恕我直言，您翻译的内容我也翻了下，除了readme注明了来源，您在每个文件中都注明了原始版权和来源了吗？未必见得吧，是不是以身作则下：）

**Comment by sunface** [comment]
本来写了一大堆想说的，想想算了，何必为自己树敌。我是觉得如果要求别人怎么怎么做，首先自己要做好，而不是没有深入阅读书籍，就洋洋洒洒引经据典的提出自己的看上去华丽的观点，真的，大家都不是傻子，不如开诚布公的说出你的真实想法。

你引用的todo里面的链接，写的是一个reddit的论坛帖子，里面的观点还没有形成体系化，如果我每一篇文章都要把几十处借鉴的地方列出来，这书会成什么样？

你说的有借必标，请问自己做到了吗？

你说的你不太舒服，那你没有深入阅读，就轻飘飘说别人是翻译和搬运工，请问你尊重他人了吗？他人舒服吗？

你说Readme里的感谢只是空洞的，那你觉得你的理解就是正确的吗？

你说协议授权，那请问我做的事情违反这些书的哪些授权了？

最后，您翻译的书中，每一篇文章都标记了各种版权和链接了吗？

树欲静而风不止，我本想老老实实写书，但是非要有人跳出来无端指责，那便战吧。

最后，如果你深入阅读过，还觉得我只是一个搬运工，那么我愿意为此处的"无礼"道歉：） 否则，你应该考虑向我道歉下，

**Comment by codemystery** [comment]
作为该项目的参与者，感觉到一丝丝的酸味

**Comment by sunface** [comment]
我的观点已经表达清楚，你的建议我也会考虑，这个issue就先关闭了，不然别人还以为我是在抄袭

**Comment by sunface** [comment]
嗯，希望你和你尊重的人在过去、现在和未来都能保证自己引用的一切内容都标明了来源，这样，我确实会对你心服口服。

**Comment by sunface** [comment]
不过还是那句话，我会在后面看看如何对一些重要的、大块的借鉴标注下来源，最后，感谢你的提醒，这个我还是真心的～～
