### ISSUE TITLE
建议固定一下rust playground运行的版本

### ISSUE THREAD

**Issue by chenxuuu** [sunface/rust-course#160]
比如[这里的代码](https://course.rs/advance/functional-programing/iterator.html#next%E6%96%B9%E6%B3%95)，因为默认用的2018版本运行，会报错：

```rust
fn main() {
    let arr = [1, 2, 3];
    let mut arr_iter = arr.into_iter();

    assert_eq!(arr_iter.next(), Some(1));
    assert_eq!(arr_iter.next(), Some(2));
    assert_eq!(arr_iter.next(), Some(3));
    assert_eq!(arr_iter.next(), None);
}
```

不知道用的是不是mdbook，如果是的话，最好可以[固定用2021版本](https://rust-lang.github.io/mdBook/format/configuration/general.html#rust-options)

**Comment by sunface** [comment]
是用的mdbook，如果可以，大佬帮忙提个PR  🌹

**Comment by chenxuuu** [comment]
不是大佬，还是个在看教程的小菜鸡的😂
