### ISSUE TITLE
@绑定新的特性已经在1.56版本中稳定，但书中好像没有提及

### ISSUE THREAD

**Issue by linqingyao** [sunface/rust-course#180]
查看 rust-course 书籍并没有发现关于 @ 绑定 在 1.56版本中稳定的新的特性，建议加入。
详细链接参考：
https://github.com/rust-lang/rust/issues/65490#issuecomment-841999009

**Comment by sunface** [comment]
好的。。。我看看，感谢提醒

**Comment by linqingyao** [comment]
Ok，Ok

**Comment by sunface** [comment]
等我加进去后再关 😆

**Comment by sunface** [comment]
已更新，再次感谢～～
