### ISSUE TITLE
函数中return 后需要分号

### ISSUE THREAD

**Issue by shenshouer** [sunface/rust-course#195]
https://github.com/sunface/rust-course/blob/f2c21798bd56d35e37a9e1023423448d870ca868/book/contents/basic/base-type/function.md?plain=1#L75 
与 
https://github.com/sunface/rust-course/blob/f2c21798bd56d35e37a9e1023423448d870ca868/book/contents/basic/base-type/function.md?plain=1#L95 

函数中return 后需要分号：

```
fn plus_or_substract(x:i32) -> i32 {
    if x > 5 {
        return x - 5                 <------- here
    }

    x + 5
}
```

**Comment by sunface** [comment]
感谢告知，不过这里不加也可以的:)
