### ISSUE TITLE
关于2.4章复合类型的章节排列

### ISSUE THREAD

**Issue by AllanDowney** [sunface/rust-course#200]
在`2.4.复合类型`章节末
> 接下来，我们将引入一个高级数据结构 - 结构体`struct`，来看看复合类型是怎样更好的解决这类问题。 开始之前，先来看看什么是`元组`.

下一节不是`元组`，而是`2.4.1字符串与切片`

看到这里有断片儿的感觉，是不是能重新编排下顺序？

**Comment by sunface** [comment]
已解决
