### ISSUE TITLE
教程质量不错，赞一个

### ISSUE THREAD

**Issue by Yinnae** [sunface/rust-course#212]
认真浏览了你们的教程，内容质量还是不错的。

这样质量的免费教程，其实不刷什么僵尸粉，我们也会自己点赞的。

相对于高质量的内容，我们更需要内容生产者的诚信和认真，而不是把经历放在这些弄虚作假的事情上。

**Comment by sunface** [comment]
感谢提醒，但是有没有弄虚作假，我心里很清楚～

**Comment by sunface** [comment]
如果真有弄虚作假，我也有理由怀疑是有不良居心的人故意来反串的，身正不怕影子歪

**Comment by sunface** [comment]
再多嘴一句。。你的号也太新了吧，有意思～～！
