### ISSUE TITLE
老鼠出洞02 - 请附上媒体报道说明，证明Star合法来源

### ISSUE THREAD

**Issue by HIKVisio** [sunface/rust-course#253]
![image](https://user-images.githubusercontent.com/98039169/150162111-84391c5c-412f-467d-b261-dc30816df518.png)
![image](https://user-images.githubusercontent.com/98039169/150162188-f74f9187-916b-4291-870e-7b0dea47833e.png)

长时间无人问津项目，为何短时间获得如此只多Star？请说明！

**Comment by sunface** [comment]
呦黑子又来了，你的智商还足以理解，从一个无用的项目切换到另外一个项目吧？

**Comment by sunface** [comment]
还有，能不能不要开小号了啊，你是活在老鼠窝里吗？注册于7个小时前的小号？哈哈

**Comment by sunface** [comment]
重复黑，我先关了，具体见 #242
