### ISSUE TITLE
内容优化建议请至 Discussions 板块讨论

### ISSUE THREAD

**Issue by sunface** [sunface/rust-course#260]
大家如果对内容有建议，可以移步到[Discussions板块](https://github.com/sunface/rust-course/discussions)进行讨论。

你们的建议非常宝贵，可以帮助rust-course在未来成为更好的开源 Rust 教程，感谢感谢😆。

> 目前还无法提供内容上的答疑解惑。。因为笔者时间实在有限，敬请谅解 :(

**Comment by JesseAtSZ** [comment]
[生命周期](https://course.rs/advance/lifetime/advance.html)
71行，这里的因果关系貌似颠倒了？应该是返回值的生命周期由入参的生命周期决定。
125行，没读懂无解生命周期与普通生命周期的区别
160行，为什么一个类型存在生命周期，我理解生命周期只存在于引用中，所以这里拿一个类型和一个引用的生命周期比较，有点不太理解

**Comment by alanhe** [comment]
> Rust 的集合类型不能直接进行循环
https://github.com/sunface/rust-course/blob/main/book/contents/first-try/hello-world.md?plain=1#L46

但是，去掉 `iter` 也可以编译运行的。
```rust
for region in regions {
    println!("{}", &region);
}
```

**Comment by sunface** [comment]
> > Rust 的集合类型不能直接进行循环
> > https://github.com/sunface/rust-course/blob/main/book/contents/first-try/hello-world.md?plain=1#L46
> 
> 但是，去掉 `iter` 也可以编译运行的。
> 
> ```rust
> for region in regions {
>     println!("{}", &region);
> }
> ```

这个在迭代器章节的开头有讲，是因为`for`隐式地将`regions`转换成迭代器

**Comment by butonly** [comment]
https://course.rs/basic/base-type/index.html
`元类型` 译为 `单元类型` 是否更好一些？

**Comment by sunface** [comment]
我先关闭issue了，因为该issue是引导贴，建议和讨论请移步到[Discussions板块](https://github.com/sunface/rust-course/discussions/landing)

**Comment by sunface** [comment]
> https://course.rs/basic/base-type/index.html
> https://github.com/sunface/rust-course/blob/main/book/contents/basic/base-type/index.md
> `元类型` 译为 `单元类型` 是否更好一些？

我很认同，因为元类型其实会跟`meta type`冲突，兄弟你可以去[讨论区](https://github.com/sunface/rust-course/discussions) 开个讨论帖，大家一起讨论下

**Comment by sunface** [comment]
我先关闭issue了，因为该issue是引导贴，建议和讨论请移步到[Discussions板块](https://github.com/sunface/rust-course/discussions/landing)
