### ISSUE TITLE
Star数量为何剧烈减少？是因为Rust太难，大家放弃了？对中国开源事业有和影响？

### ISSUE THREAD

**Issue by Yinnae** [sunface/rust-course#356]
看到 #253 帖子中，19日的Star数量2584颗，然而现在开只有2064颗，这500名真实的同学是太难而放弃了吗？

<img width="893" alt="截屏2022-01-28 14 01 59" src="https://user-images.githubusercontent.com/97794355/151496422-22cb8472-9a44-4617-9e6f-c42fcdae9575.png">

对你们的质疑是处于好心和实事求是的态度，请不要诬蔑这些善良的人 #242

**Comment by Yinnae** [comment]
19日的状态——

![image](https://user-images.githubusercontent.com/97794355/151496586-0dec1d2c-a203-4f4b-893f-ab869d348e46.png)

**Comment by sunface** [comment]
哦呦，又来了？八成你举报的吧？结果我看了下，很多本来只关注、不怎么干其它事(有些人本来就是用github来作为一个阅读途径)的账号的star，都被取消了。。我也是服了，github 竟然会相信你这种黑子的话，你用了多少号去举报？

像你这样黑我的执着劲，至少用了几十个号举报吧？

不过，好在，还留下了这么多star ，足以证明这个项目的质量之高。。

我还是劝你们一句，好好做内容，少干这些偷鸡摸狗的事情，摸着自己的良心，不痛吗？
