### ISSUE TITLE
关于md文本格式规范

### ISSUE THREAD

**Issue by suhanyujie** [sunface/rust-course#388]
Hello all~
不知道现在编写的 markdown 文本是否有遵循的标准呢？推荐按照[中文排版指南 ](https://github.com/sparanoid/chinese-copywriting-guidelines)，这样编写、校审就有遵循的标准了。此外，掘金翻译社区的 [md 文档](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)也是遵循类似的规范。

**Comment by sunface** [comment]
目前并没有标准，非常感谢提供的参考链接，很有价值 :)
