### ISSUE TITLE
迭代器 - 消费者适配器

### ISSUE THREAD

**Issue by kaichii** [sunface/rust-course#431]
[具体位置](https://course.rs/advance/functional-programing/iterator.html#:~:text=%E5%99%A8%E4%B8%AD%E7%9A%84%E5%85%83%E7%B4%A0%EF%BC%8C-,%E7%84%B6%E5%90%8E%E8%BF%94%E5%9B%9E%E5%85%B6%E5%AE%83%E7%B1%BB%E5%9E%8B%E7%9A%84%E5%80%BC,-%EF%BC%8C%E8%BF%99%E4%BA%9B%E6%B6%88%E8%B4%B9%E8%80%85)，是不是多了个 ”它“？

**Comment by sunface** [comment]
额。。要不提交 `pr`，我这边点链接没有看到具体的位置。。

**Comment by kaichii** [comment]
好像不多诶（如果我理解错了的话）
