### ISSUE TITLE
个人看法：建议把这段重新组织一下

### ISSUE THREAD

**Issue by tomoat** [sunface/rust-course#453]
**两种循环方式优劣对比**

以下代码，使用了两种循环方式：
```rust
// 第一种
let collection = [1, 2, 3, 4, 5];
for i in 0..collection.len() {
  let item = collection[i];
  // ...
}

// 第二种
for item in collection {

}
```

第一种方式是循环索引，然后通过索引下标去访问集合，第二种方式是直接循环集合中的元素，优劣如下：

- **性能**：第一种使用方式中 `collection[index]` 的索引访问，会因为边界检查(Bounds Checking)导致运行时的性能损耗 —— Rust会检查并确认 `index` 是否落在集合内，但是第二种直接迭代的方式就不会触发这种检查，因为编译器会在编译时就完成分析并证明这种访问是合法的
- **安全**：第一种方式里对 `collection` 的索引访问是非连续的，存在一定可能性在两次访问之间，`collection` 发生了变化，导致脏数据产生。而第二种直接迭代的方式是连续访问，因此不存在这种风险（这里是因为所有权吗？是的话可能要强调一下）

由于 `for` 循环无需任何条件限制，也不需要通过索引来访问，因此是最安全也是最常用的，通过与下面的 `while` 的对比，我们能看到为什么 `for` 会更加安全。

**Comment by tomoat** [comment]
个人看法：建议把这段重新组织一下，从结果来说这两种方式完全没有可比性，一般来说比较的话，都是各有优劣，但是这两种完全是第一种全部是缺点，第二种也没写出缺点全是优点，这个比较感觉很没有意义，从结果看：能循环collection,没有必要去循环collection的索引，并且循环索引不管是性能还是安全都有问题

**Comment by sunface** [comment]
但是循环索引确实是很多语言或者程序员喜欢或常用的方式，所以将其跟 Rust 推荐的方式放在一起比较。

**Comment by tomoat** [comment]
就是感觉这段有点啰嗦，第一种不管从性能和安全都不推荐，尽量避免第一种写法就行，第一种写法总有点脱裤子放屁的感觉（不是对人啊），也很少人这样写（没想到只能循环索引而不能循环本身的例子），哈哈哈

**Comment by tomoat** [comment]
比较的话一般都是各有优劣，但是上面这两种只是不同人的写法，并不是语言本身语法，并且第一种从结果看完全没有优点啊

**Comment by sunface** [comment]
无论如何，感谢建议，我想想怎么组织会更好。 这两种比较其实还有一个目的：用于说明迭代的性能为什么会好
