### ISSUE TITLE
Remove the misleading AWS "Sustainability with Rust" use case

### ISSUE THREAD

**Issue by 1132719438** [sunface/rust-course#482]
The comparsion between Go and Rust is misleading.

> The original Discord post showed a single graph plotting both a Go server and the equivalent Rust server. The Rust line had more predictable performance and avoided the latency spikes in the Go line, but the lines were roughly comparable

> Instead, the AWS post displayed the Go graph next to a graph of the Rust server after a significant rewrite to use new data structures and more RAM, circling “ms” vs “µs” time scales. This is either a complete misunderstanding of the Discord post or blatant dishonesty

ref https://twitter.com/_rsc/status/1496352325157457922

**Comment by sunface** [comment]
嗯，这个我看过，先不删除了, AWS有勇气发，我们就有勇气引用，这篇文章的总体含义是没大问题的，瑕不掩瑜，对于 Rust 的宣传有很好的正面作用。
