### ISSUE TITLE
1.3 认识cargo结尾的地方   详细的说明参见此章：Cargo 依赖管理 链接好像失效了

### ISSUE THREAD

**Issue by digger-yu** [sunface/rust-course#518]
![图片](https://user-images.githubusercontent.com/55081697/156678403-299cebf2-70e5-4afc-8e65-442b1f591970.png)

详细的说明参见此章：[Cargo 依赖管理](https://course.rs/cargo/dependency.html)

[Document not found (404)](https://course.rs/#document-not-found-404)

This URL is invalid, sorry. Please use the navigation bar or search to continue.

**Comment by sunface** [comment]
感谢提示，已修复 😋
