### ISSUE TITLE
tokio章节的深入async一节url跳转问题

### ISSUE THREAD

**Issue by yzecho** [sunface/rust-course#534]
<img width="1438" alt="截屏2022-03-08 11 07 41" src="https://user-images.githubusercontent.com/38834224/157158857-48adf6e0-4fc0-41b9-a098-4cefc81c722e.png">

结果会引导在新的不正确的url地址：
<img width="447" alt="截屏2022-03-08 11 10 58" src="https://user-images.githubusercontent.com/38834224/157158962-5dbf15ce-e615-4dc2-80b9-728f2c89f6a7.png">

**Comment by sunface** [comment]
好的，我看看～～ 谢谢反馈

**Comment by sunface** [comment]
已解决
