### ISSUE TITLE
[是否上传本地的 Cargo.lock] 中文字缺少

### ISSUE THREAD

**Issue by taotieren** [sunface/rust-course#550]
![image](https://user-images.githubusercontent.com/13965460/157786271-914e59b4-aa63-4829-84c4-15a32ffa1faa.png)
原始：若构建的是一个面向用户终端的产品，例如可以像命令行工具、应用程一样执行，那就把 Cargo.lock 上传到源代码目录中。
修改：若构建的是一个面向用户终端的产品，例如可以像命令行工具、应用程序一样执行，那就把 Cargo.lock 上传到源代码目录中。

**Comment by sunface** [comment]
感谢告知，可以在线提一个 pr :)

**Comment by taotieren** [comment]
可以，还有好几处

**Comment by sunface** [comment]
merged :)
