### ISSUE TITLE
内存对象是否严谨？

### ISSUE THREAD

**Issue by NaturelLee** [sunface/rust-course#565]
https://course.rs/basic/variable.html

![image](https://user-images.githubusercontent.com/12494855/158293401-b7da607c-b97f-4a82-bb34-88a17c7d61b4.png)

不太清楚使用内存对象是否严谨。内存对象改为内存是否更好？

**Comment by sunface** [comment]
我觉得应该是合理的，内存对象其实比内存更准确点，或者更能达意

**Comment by sunface** [comment]
这个问题确实可以讨论下，因为堆内存对象，肯定是合理的，而且具有非常清晰准确的含义，要比内存更能达意。

现在的问题是，栈内存对象分配和栈内存分配，哪个更好 ：）

**Comment by Rustln** [comment]
由于变量遮蔽实际上是创建了新的内存数据，而且这个数据可能是基元类型（栈分配）亦或是复合类型（堆分配）数据，但它们都是内存的数据，所以这里个人认为使用`内存对象`是对的，毕竟堆和栈都是内存的主要数据结构。

只不过后面 `而 mut 声明的变量，可以修改同一个内存地址上的值，并不会发生内存对象的再分配` 这句话确实不够严谨，比如动态数组 `Vector` 的机制：`当旧数组的大小不够用时，Rust 会重新分配一块更大的内存空间，然后把旧数组拷贝过来。` 实际上也涉及到了内存再分配~~

**Comment by NaturelLee** [comment]
对象 大部分人估计看到时想到是OOP中的对象

**Comment by Rustln** [comment]
> 对象 大部分人估计看到时想到是OOP中的对象

haha，这么解释是对的~~，从这个角度来看，确实 `内存` 比 `内存对象` 更合适，毕竟 `Rust` 不是严格语言上的 `面向对象语言`。

**Comment by sunface** [comment]
内存对象在很多语言中都有这个说法的

**Comment by sunface** [comment]
先关了
