### ISSUE TITLE
Can this be in English?

### ISSUE THREAD

**Issue by lukaskretzschmer** [sunface/rust-course#718]
The title.

**Comment by sunface** [comment]
It would need significant amout of work to translate into English 🤣

**Comment by Caviar-X** [comment]
Well,why?I mean that there's a huge amount of good tourtorials in English community and there's little high-quality source about rust in Chinese community.
Of course,it requires a lot of people and time to translate.Maybe I will do it later (in Jul or Aug).
Sorry for my bad English XD.
