### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by meggarr** [sunface/rust-course#809]
一个小小的建议，不要用”圣经“这个词，一是有宗教色彩，而是圣经是无脑相信的，和教程的目的不相符。建议用：”讲义“，”讲座“，”课程“，或者一些中性的词语更好，更随和。:-)

**Comment by sunface** [comment]
建议收到，但是没办法修改了。

所有的搜索引擎收录、相关的博客平台&社区、用户已知的概念，都是以这个名字为基础的，改动后的成本非常高，意味着过去半年的搜索引擎排名慢慢爬升全部白废了。

但是还是谢谢你的建议哈～
