### ISSUE TITLE
在每一节的最下面加两个按钮可以直接下一节或者上一节

### ISSUE THREAD

**Issue by likzn** [sunface/rust-course#843]
感觉可以在这两个红框这里加两个button对应上一节或者下一节。这样就不用点击侧边栏了。
![image](https://user-images.githubusercontent.com/39450062/166093430-6474eb8b-690d-4ee1-8331-60d00023eed2.png)

**Comment by sunface** [comment]
谢谢建议，我看看现有的框架内好不好改

**Comment by likzn** [comment]
> 谢谢建议，我看看现有的框架内好不好改

整个站点都是用rust编写的吗。如果这个好改的话，可以帮忙指点下，我这边来实现下哈哈：）

**Comment by sunface** [comment]
是基于 mdbook，这个框架是 rust 写的，但是，实际上需要修改的地方应该是 js 部分。🤣
