### ISSUE TITLE
mdbook 会把泛型的尖括号解析为 HTML 标签

### ISSUE THREAD

**Issue by glatavento** [sunface/rust-course#859]
例如
https://github.com/sunface/rust-course/blob/cfc2f5f779eb0a187a43e7e0ea5ebf9138edb30f/src/advance/concurrency-with-threads/sync1.md?plain=1#L152
变成了[这样](https://course.rs/advance/concurrency-with-threads/sync1.html#%E5%A4%9A%E7%BA%BF%E7%A8%8B%E5%AE%89%E5%85%A8%E7%9A%84-arc)，`<T>` 没有了
![图片](https://user-images.githubusercontent.com/76601050/167749303-0eea610e-18e8-469f-837e-1a3ee879a4ea.png)
类似情况还有
https://github.com/sunface/rust-course/blob/1aa9a94ec52370f9577b528b6590eea1c9bcce6b/src/advance/errors.md?plain=1#L524
https://github.com/sunface/rust-course/blob/a5079e1bb51ffef36dcf0f196440bdd3cd70921e/src/advance/into-types/sized.md?plain=1#L105
https://github.com/sunface/rust-course/blob/3222ba1b35c6dfc32943c1d56b910a8053822028/src/advance/smart-pointer/rc-arc.md?plain=1#L12
https://github.com/sunface/rust-course/blob/3222ba1b35c6dfc32943c1d56b910a8053822028/src/advance/smart-pointer/rc-arc.md?plain=1#L147

**Comment by sunface** [comment]
我去，还有这个问题，我看一下哈，可能要都要加个转译了。如果不介意的话，可以提个 PR 😆
