### ISSUE TITLE
想要解决的Rust问题

### ISSUE THREAD

**Issue by sunface** [sunface/rust-course#88]
Rust有三难
1. 部分概念难以理解
2. 语法太多，难以学习，而且较为分散，有的时候忘记了不好查找
3. 实际上手写代码，需要注意的点很多，缺乏一个上手和避坑指南，也缺乏一个常见问题汇总，提前学习这些可以显著的减少在实际项目中遇到问题不知道该怎么办的情况

**Comment by Robert-Ro** [comment]
[codewars](https://www.codewars.com/dashboard)中的`Rust`练习能满足需求吗

**Comment by jiacai2050** [comment]
我之前写过一篇文章，就是介绍 Rust 中的 gotchas，供参考：
- https://liujiacai.net/blog/2021/12/25/rust-gotchas/
