### ISSUE TITLE
设置依赖解析器( dependency resolver) 相关章节缺失

### ISSUE THREAD

**Issue by likzn** [sunface/rust-course#890]
Hi,问下这个跳转是404。是还在更新路上吗，还是上传的时候漏了~
https://github.com/sunface/rust-course/blob/abf94cabe7e1bcd267d1006779e7397bea0b3a49/src/cargo/reference/manifest.md?plain=1#L33

**Comment by sunface** [comment]
你好。。。是链接错了，因为这块儿东西太小众了，所以并没有进行翻译的计划🤣
